      - name: 编译 dylib
        run: |
          clang -arch arm64 \
            -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
            -framework UIKit \
            -framework Foundation \
            -framework QuartzCore \
            -lobjc \
            -miphoneos-version-min=15.0 \
            -fobjc-arc \
            -dynamiclib \
            -O2 \
            -Wl,-undefined,dynamic_lookup \
            iphook.m \
            -o iphook.dylib
