name: Build Dylib
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Fetch iOS SDK Path
        run: echo "IOS_SDK=$(xcodebuild -version -sdk iphoneos Path)" >> $GITHUB_ENV

      - name: Compile iOS arm64 dylib
        run: |
          clang -dynamiclib \
          -arch arm64 \
          -mios-version-min=15.0 \
          -isysroot ${{ env.IOS_SDK }} \
          -framework Foundation \
          -fobjc-arc \
          kfun_bypass.m -o kfun_bypass.dylib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kfun_bypass-dylib
          path: kfun_bypass.dylib
